doctrine:
    orm:
        auto_generate_proxy_classes: false
        query_cache_driver:
            type: pool
            pool: redis.cache
        result_cache_driver:
            type: pool
            pool: redis.cache
        metadata_cache_driver:
            type: pool
            pool: redis.cache

framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: redis://localhost
        pools:
            redis.cache:
                adapter: cache.adapter.redis
