# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\UseCase\User\Register\RegisterHandler:
        tags: [{ name: messenger.message_handler, bus: command.bus }]
        autoconfigure: false
    App\UseCase\User\List\ListHandler:
        tags: [{ name: messenger.message_handler, bus: query.bus }]
        autoconfigure: false
    App\UseCase\Task\Register\RegisterHandler:
        tags: [{ name: messenger.message_handler, bus: command.bus }]
        autoconfigure: false
    App\UseCase\Task\Toggle\ToggleHandler:
        tags: [{ name: messenger.message_handler, bus: command.bus }]
        autoconfigure: false
    App\UseCase\Task\Delete\DeleteHandler:
        tags: [{ name: messenger.message_handler, bus: command.bus }]
        autoconfigure: false
    App\UseCase\Task\List\ListHandler:
        tags: [{ name: messenger.message_handler, bus: query.bus }]
        autoconfigure: false