name: Continuous Integration
on: [push]
jobs:
  ci:
    name: Continuous Integration
    env:
      DATABASE_URL: "mysql://root:Password123!@172.18.0.1:3306/todoandco?serverVersion=8.0.21"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.1']
        node-version: ['12.18.2']
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 'Password123!'
        ports:
          - 3306:3306
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl
          coverage: xdebug
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install
        run: |
          composer install
          npm install
          npm run dev
          php bin/console d:d:c --env=test
          php bin/console d:s:u -f --env=test
          php bin/console d:f:l -n --env=test
      - name: Analyze
        run: vendor/bin/phpstan
      - name: Tests
        run: vendor/bin/phpunit